// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using obss1.Models;

namespace obss1.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20220223195712_deneme1")]
    partial class deneme1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("obss1.Models.StudentModel", b =>
                {
                    b.Property<string>("courseName")
                        .HasColumnType("text");

                    b.Property<int>("firstExam")
                        .HasColumnType("integer");

                    b.Property<Guid>("id")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<bool>("passState")
                        .HasColumnType("boolean");

                    b.Property<int>("secondExam")
                        .HasColumnType("integer");

                    b.Property<string>("studentNumber")
                        .HasColumnType("text");

                    b.Property<string>("surname")
                        .HasColumnType("text");

                    b.ToTable("studentModels");
                });
#pragma warning restore 612, 618
        }
    }
}
